# Generated by Django 3.1.1 on 2020-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
