# Generated by Django 3.1.1 on 2020-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0002_auto_20200909_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='loan_end_time',
        ),
        migrations.AddField(
            model_name='equipment',
            name='info',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
