# Generated by Django 3.1.1 on 2020-09-08 15:26

from django.db import migrations, models
import webSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0002_systemuser_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='examining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='examining_status',
            field=models.SmallIntegerField(default=webSystem.models.ExamStatus['NORMAL']),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='info_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='info_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='info_lab',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='info_tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
