# Generated by Django 3.1.1 on 2020-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0003_remove_systemuser_examining'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='examining',
            field=models.BooleanField(default=False),
        ),
    ]
