# Generated by Django 3.1.1 on 2020-09-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0004_systemuser_examining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='examining',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_provider',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_student',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='info_reject',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
