# Generated by Django 3.1.1 on 2020-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0004_auto_20200908_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='examining_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
