# Generated by Django 3.1.1 on 2020-09-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0005_auto_20200909_1535'),
        ('webSystem', '0003_auto_20200909_1655'),
    ]

    operations = [
    ]
