# Generated by Django 3.1.1 on 2020-09-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0005_auto_20200908_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='examining_status',
        ),
    ]
