# Generated by Django 3.1.1 on 2020-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0006_remove_systemuser_examining_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='examining_status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
