# Generated by Django 3.1.1 on 2020-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0006_merge_20200909_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='examining_status',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='info_reject',
            field=models.TextField(default='', max_length=200),
        ),
    ]
