# Generated by Django 3.1.1 on 2020-09-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0006_merge_20200909_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='loan_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='loan_start_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loaner',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='logged',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='statement',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
