# Generated by Django 3.1.1 on 2020-09-08 16:34

from django.db import migrations, models
import webSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0007_systemuser_examining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='examining_status',
            field=models.PositiveSmallIntegerField(default=webSystem.models.ExamStatus['NORMAL']),
        ),
    ]
