# Generated by Django 3.1.1 on 2020-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0008_merge_20200910_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='response',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
