# Generated by Django 3.1.1 on 2020-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0009_loanapplication_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='verif_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
