# Generated by Django 3.1.1 on 2020-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0011_mail_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='info_reject',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='response',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='info_reject',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='verif_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
