# Generated by Django 3.1.1 on 2020-09-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0011_mail_systemlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemlog',
            old_name='send_time',
            new_name='operate_time',
        ),
        migrations.RenameField(
            model_name='systemlog',
            old_name='sender',
            new_name='operator',
        ),
    ]
