# Generated by Django 3.1.1 on 2020-09-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0012_auto_20200912_1459'),
        ('webSystem', '0014_auto_20200912_1557'),
    ]

    operations = [
    ]
