# Generated by Django 3.1.1 on 2020-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0015_merge_20200912_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='relatedID',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mail',
            name='type',
            field=models.CharField(default='Hit', max_length=20),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
