# Generated by Django 3.1.1 on 2020-09-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0016_auto_20200912_1803'),
        ('webSystem', '0016_auto_20200912_1823'),
    ]

    operations = [
    ]
