# Generated by Django 3.1.1 on 2020-09-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0017_merge_20200912_1303'),
        ('webSystem', '0017_merge_20200912_2029'),
    ]

    operations = [
    ]
