# Generated by Django 3.1.1 on 2020-09-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSystem', '0018_merge_20200912_1655'),
        ('webSystem', '0018_merge_20200913_0116'),
    ]

    operations = [
    ]
